// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4c1itVSi2QSBDegCT7OID3vX5VjHz5wE',
    appId: '1:835491248005:web:886502e32a9a37eb7276ec',
    messagingSenderId: '835491248005',
    projectId: 'student-data-40b00',
    authDomain: 'student-data-40b00.firebaseapp.com',
    storageBucket: 'student-data-40b00.appspot.com',
    measurementId: 'G-KHKQKXX47J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw7zbgvBmQSMY6cnNKLTpny4JsB5Qfhus',
    appId: '1:835491248005:android:0407e77a3fa3beaa7276ec',
    messagingSenderId: '835491248005',
    projectId: 'student-data-40b00',
    storageBucket: 'student-data-40b00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsmeX3Ji40CjlImPJ0FcpTtIBi19DYPS0',
    appId: '1:835491248005:ios:d95553dd8602787e7276ec',
    messagingSenderId: '835491248005',
    projectId: 'student-data-40b00',
    storageBucket: 'student-data-40b00.appspot.com',
    iosBundleId: 'com.example.databaseManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsmeX3Ji40CjlImPJ0FcpTtIBi19DYPS0',
    appId: '1:835491248005:ios:d95553dd8602787e7276ec',
    messagingSenderId: '835491248005',
    projectId: 'student-data-40b00',
    storageBucket: 'student-data-40b00.appspot.com',
    iosBundleId: 'com.example.databaseManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4c1itVSi2QSBDegCT7OID3vX5VjHz5wE',
    appId: '1:835491248005:web:b43dee3074473d587276ec',
    messagingSenderId: '835491248005',
    projectId: 'student-data-40b00',
    authDomain: 'student-data-40b00.firebaseapp.com',
    storageBucket: 'student-data-40b00.appspot.com',
    measurementId: 'G-ZT43TBPF4E',
  );
}
